program: parent.c child.c signal.c asigact.c readPipe.c writePipe.c
	gcc -Wall -o program parent.c
	gcc -Wall -o child child.c
	gcc -Wall -o signal signal.c
	gcc -Wall -o asigact asigact.c
	gcc -Wall -o readPipe readPipe.c
	gcc -Wall -o writePipe writePipe.c





child: child.c
	gcc -Wall -o child child.c
clean:
	rm -rf program child signal asigact readPipe writePipe